# Generated by Django 6.0.8 on 2026-08-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='laboratorios.laboratorio')),
            ],
        ),
    ]
