# Generated by Django 6.0.8 on 2026-08-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('capacidade', models.PositiveIntegerField()),
                ('bloco', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
